platform :ios, '5.0'
pod 'Reachability', '~> 3.1.0'
pod 'AFNetworking', '~> 1.2.0'
pod 'FormatterKit', '~> 1.1.1'
pod 'PSAlertView', '~> 1.1'
pod 'SVProgressHUD', '~> 0.9'
pod 'ECSlidingViewController', '~> 0.9.0'
pod 'HockeySDK', '~> 3.0.0'
pod 'Appirater', '~> 1.0.1'
pod 'Dropbox-iOS-SDK', '~> 1.3.4'
pod 'Facebook-iOS-SDK', '~> 3.2.1'
